//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AFA> AFA { get; set; }
        public DbSet<FizetesMod> FizetesMod { get; set; }
        public DbSet<Kategoria> Kategoria { get; set; }
        public DbSet<Megrendeles> Megrendeles { get; set; }
        public DbSet<MegrendelesTetel> MegrendelesTetel { get; set; }
        public DbSet<Statusz> Statusz { get; set; }
        public DbSet<Telephely> Telephely { get; set; }
        public DbSet<Termek> Termek { get; set; }
        public DbSet<Vevo> Vevo { get; set; }
    }
}
