//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizetesMod
    {
        public FizetesMod()
        {
            this.Megrendeles = new HashSet<Megrendeles>();
        }
    
        public int ID { get; set; }
        public string Mod { get; set; }
        public Nullable<int> Hatarido { get; set; }
    
        public virtual ICollection<Megrendeles> Megrendeles { get; set; }
    }
}
