//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephely
    {
        public Telephely()
        {
            this.Megrendeles = new HashSet<Megrendeles>();
            this.KozpontiTelephelye = new HashSet<Vevo>();
        }
    
        public int ID { get; set; }
        public string IR { get; set; }
        public string Varos { get; set; }
        public string Utca { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public Nullable<int> VevoID { get; set; }
    
        public virtual ICollection<Megrendeles> Megrendeles { get; set; }
        public virtual Vevo Vevo { get; set; }
        public virtual ICollection<Vevo> KozpontiTelephelye { get; set; }
    }
}
